Repository Pocket-SOL/BE, pull requests merged in 2024-11, with the labels that each got.

#5 Fix : modify config code
  config/mysql.js
  config/server.js
Labels: bug

#11 chore : set swagger
  app.js
  config/swagger.js
  package-lock.json
  package.json
Labels: enhancement

#14 Feat : make model(#13)
  app.js
  config/config.js
  models/account.js
  models/activitylog.js
  models/comment.js
  models/history.js
  models/index.js
  models/init-models.js
  models/mission.js
  models/purchase.js
  models/purchaseuser.js
  models/subaccount.js
  models/subaccounthistory.js
  models/user.js
  package-lock.json
  package.json
  routes/users.js
Labels: enhancement

#15 Feat : make account api
  app.js
  config/table.js
  models/history.js
  models/index.js
  routes/accounts.js
Labels: enhancement

#16 Feat : make get account history api(#10)
  app.js
  routes/accounts.js
Labels: enhancement

#19 chore : set prettier
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
Labels: 환경설정

#21 Feature/9 users
  config/table.js
  models/user.js
  package-lock.json
  package.json
  routes/users.js
Labels: 구현

#23 Feat : make send amount api
  models/index.js
  routes/accounts.js
  util/account_const.js
Labels: 구현

#25 chore : make relation in model
  app.js
  models/account.js
  models/comment.js
  models/history.js
  models/index.js
  models/mission.js
  models/purchase.js
  models/purchaseuser.js
  models/scheduledtransfer.js
  models/subaccount.js
  models/subaccounthistory.js
  models/user.js
Labels: 구현

#26 Feature/8 purchase api
  app.js
  models/comment.js
  models/index.js
  models/purchase.js
  package-lock.json
  routes/comment.js
  routes/purchases.js
Labels: 구현

#28 Feature/9 users
  app.js
  routes/users.js
Labels: 구현

#29 Feat/22 get sub account
  routes/accounts.js
  routes/subaccounts.js
  util/account_const.js
Labels: 구현

#32 Feat : make account withdrawals get api(#31)
  models/index.js
  routes/accounts.js
Labels: 구현

#34 Feat : add account withdrawal swagger(#33)
  routes/accounts.js
Labels: documentation

#39 Feat : make deploy.yml (#38)
  .github/workflows/deploy.yml
Labels: 환경설정

#40 Feature/27 api connect
  app.js
  middlewares/userAuth.js
  routes/comment.js
  routes/purchases.js
  routes/users.js
Labels: 구현

#37 Feature/9 users
  models/index.js
  models/user.js
  routes/users.js
Labels: fix, 구현

#41 Feature : add Dockerfile(#38)
  Dockerfile
Labels: 환경설정, 구현

#45 Fix : modify subaccount-user
  routes/subaccounts.js
Labels: bug

#46 Fix : modify deploy.yml(#38)
  .github/workflows/deploy.yml
Labels: fix

#49 Feat : make get account number api(#48)
  config/swagger.js
  models/account.js
  models/index.js
  routes/accounts.js
Labels: 구현

#51 Feat : make get history detail api(#50)
  app.js
  routes/histories.js
Labels: 구현

#54 Fix : modify env route
  .github/workflows/deploy.yml
Labels: bug

#60 [Feat] make s3 upload function & image upload api
  config/bucket.js
  config/multer.js
  package-lock.json
  package.json
  routes/histories.js
Labels: 구현

#61 Feat : make img url put api on histories(#55)
  routes/histories.js
Labels: 구현

#62 Fix : modify filesize limit(#55)
  config/multer.js
Labels: fix

#66 Fix : add model update/delete option
  models/activitylog.js
  models/index.js
Labels: fix

#68 Feature/67 child registration notifications
  models/childregnoti.js
  models/index.js
  routes/childregnotis.js
Labels: 구현

#73 Feat : open api token save(#63)
  models/index.js
  models/user.js
  package-lock.json
  package.json
  routes/users.js
Labels: 구현

#78 Fix : add user seq no (#63)
  models/user.js
  routes/users.js
Labels: fix, 구현
