Repository Pocket-SOL/BE, pull requests merged in 2024-12, with the labels that each got.

#83 Feat : make account & subaccount api(#82)
  models/account.js
  models/index.js
  routes/accounts.js
  routes/users.js
Labels: 구현

#84 Fix : modify index.js for sync model
  models/index.js
Labels: fix

#91 Feature/72 post open token
  package-lock.json
  package.json
  routes/users.js
Labels: 구현

#94 Feat : make get openapi user api(#72)
  routes/users.js
Labels: 구현

#98 Feat : make get school list with open api(#95)
  routes/schools.js
Labels: 구현

#100 Feat : make get open account api(#99)
  routes/accounts.js
Labels: 구현

#103 Fix : add catch error
  routes/accounts.js
Labels: fix

#108 Fix : handle open token in back(#99)
  routes/accounts.js
Labels: fix

#109 Fix : modify res(#99)
  routes/accounts.js
Labels: fix

#110 Fix : modify find subaccount balance
  routes/subaccounts.js
Labels: fix

#112 Feat : add init his when parent signup(#111)
  routes/accounts.js
Labels: 구현

#114 Fix : modify get history item desc(#113)
  routes/accounts.js
Labels: 수정

#117 Fix : modify cmd for serve web socket(#113)
  Dockerfile
Labels: 환경설정

#119 Document : account swagger(#116)
  routes/accounts.js
Labels: 문서

#123 Feat : make 1st day transfer with node-cron(#122)
  app.js
  cron/transferService.js
  cron/transferSurplus.js
  package-lock.json
  package.json
Labels: 구현

#124 Feat : add transaction in transferToFree func(#122)
  cron/transferService.js
Labels: 구현

#127 Feat : make execute scheduled transfer with cron(#122)
  cron/transferService.js
  cron/transferSurplus.js
Labels: 구현

#132 Feat : make get histories group by usage(#131)
  routes/subaccounts.js
Labels: 구현

#133 Fix : modify order(#131)
  routes/subaccounts.js
Labels: 구현, 수정
